# 開発・テスト用の設定
services:
  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/jemref
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_ENV=${RAILS_ENV:-development}
    command: bundle exec rails server -b '0.0.0.0'
    depends_on:
      - db
volumes:
  db-data: