default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: my_database_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: my_database_test
  username: postgres
  password: postgres
  host: 127.0.0.1 

production:
  <<: *default
  database: my_database_production
  url: <%= ENV['DATABASE_URL'] %>
