default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: jemref
  password: <%= ENV["PSQL_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: my_database_development

test:
  <<: *default
  database: my_database_test

production:
  <<: *default
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  # database: my_database_production

